### ISSUE TITLE
Tag new release 1.5.6

### ISSUE THREAD

**Issue by shukhrat-sky** [Comcast/mamba#120]
The PR with small changes have been merged into `develop_1.x `
https://github.com/Comcast/mamba/pull/119
Can you please tag new release `1.5.6`

**Comment by shukhrat-sky** [comment]
@jaybpierce @dcoufal can you please help with it?

**Comment by jonnybach** [comment]
Hi @shukhrat-sky.  Sorry for the delayed response.  dcoufal no longer works for Comcast and jay is out on holiday for this week.  I will create the release branch to merge 1.5.6 into main but will need approval by Jay.  We'll try to get this release tag create as soon as we can.

**Comment by shukhrat-sky** [comment]
Thanks a lot @jonnybach

**Comment by jonnybach** [comment]
No problem!

**Comment by jonnybach** [comment]
#121

**Comment by snayrouz** [comment]
Closing. Addressed above ✔️
