### ISSUE TITLE
xcode16 support 2.2.2 

### ISSUE THREAD

**Issue by kimbely0320** [Comcast/mamba#136]
### Description
version 2.2.2 also needs to support Xcode 16.

**Comment by kimbely0320** [comment]
Hello, I have created a PR regarding this [issue](https://github.com/Comcast/mamba/pull/138).

**Comment by theRealRobG** [comment]
This has been fixed and released as part of [2.3.0](https://github.com/Comcast/mamba/releases/tag/2.3.0).
