### ISSUE TITLE
Support XCode 9+

### ISSUE THREAD

**Issue by jgainfort** [Comcast/mamba#23]
Hi! The README states that the library supports XCode 9+ but is using an operator requiring XCode 9.3+.

Seems this was introduced with this commit and changing flatMap to compactMap

https://github.com/Comcast/mamba/commit/2ecd85c79771915d0bcade0d4297860862b7fd69

Is the intention still to support XCode 9+ or to move to only supporting 9.3+? Would a PR converting compactMap back to flatMap be acceptable?

**Comment by dcoufal** [comment]
Thanks for the issue writeup.

This is really a swift 4.0 -> 4.1 issue, but it was forced by the Xcode 9.3 update.

We're generally committed to supporting the latest non-beta releases of Xcode and Swift. So, we can't just switch back to flatMap as that means we would not compile for Swift 4.1.

We could either:

* Change the README to indicate we only support Xcode 9.3. This probably doesn't really help you, but at least we'd be more accurate in our description.

* Add a "preprocessor" check to use `compactMap` for 4.1 and `flatMap` for 4.0. I think this would look like `#if swift(>=4.1)` but that's just off the top of my head. If you wanted to submit that as  PR that would be fine with us.

Hope this helps.

**Comment by jgainfort** [comment]
@dcoufal 
If you accept the PR how long would you expect a new release to be made?

https://github.com/Comcast/mamba/pull/24

**Comment by dcoufal** [comment]
I'd guess within a day. if that doesn't happen, ping us/me in this ticket.

Also, you'll have to agree to the Comcast CLA before we could merge. I'm showing that you have not signed. Let me know if you have technical problems with that.

**Comment by jgainfort** [comment]
I did submit my agreement but it seems to not update. Getting a message saying it might be my email but I verified my email used for the commit is under my profile.

**Comment by dcoufal** [comment]
Yeah, I'm not sure either. I will check with our open source GitHub admins and get back to you.

**Comment by jgainfort** [comment]
Seems it was just updated. CLA signed.

**Comment by dcoufal** [comment]
Fixed and merged.

**Comment by dcoufal** [comment]
@jgainfort mamba 1.0.5 is released. Cocoapods takes a little time if that's what you're using.

**Comment by jgainfort** [comment]
@dcoufal  Thank you!
