### ISSUE TITLE
v 1.2.0 cocoapods

### ISSUE THREAD

**Issue by jgainfort** [Comcast/mamba#50]
Is it possible to get 1.2.0 onto cocoapods? I unfortunately have not been able to move off pods just yet.

**Comment by jgainfort** [comment]
Sorry if this seems pushy, but just want to bump this.

**Comment by jaybpierce** [comment]
thanks for bringing this to our attention. I'm looking into why master_1.x (which has 1.2.0 on the podspec) hasn't been merged to master.

**Comment by snaggled** [comment]
👍

**Comment by jgainfort** [comment]
@jaybpierce So all that should need to be done is
`pod trunk push mamba.podspec --verbose --allow-warnings`
Within the master_1.x branch

However this must be done by an owner. See https://github.com/Comcast/mamba/issues/35

**Comment by jaybpierce** [comment]
unfortunately, our one and only owner is OOTC at the moment and completely out of contact. It'll have to wait until he gets back.

**Comment by jaybpierce** [comment]
I'll make sure we ad some more owners to the list when he gets back #52

**Comment by jgainfort** [comment]
Understood

Is it possible to do the following or must it wait for an owner?
`pod trunk add-owner mamba someuser@someaddress.com`

If that doesn't work is there an estimate on when he returns?

**Comment by jaybpierce** [comment]
"Is it possible to do the following or must it wait for an owner?" tried out of thin hope, nope. He's on vacation for a few weeks, but he may occasionally have email access/internet. I'll send him a message and we may get lucky.

**Comment by jgainfort** [comment]
Thank you.

**Comment by jgainfort** [comment]
In the meantime I published 1.2 to a private podspec repo. So I am no longer in a hurry. Appreciate the quick response!

**Comment by dcoufal** [comment]
@jgainfort I have returned (was in China, the internet does not work that well there). Just pushed 1.2.0 to trunk, so you can move off your private pod spec if you want.

Sorry! We're carthage users so we don't notice when we screw up a release on pods.

**Comment by jgainfort** [comment]
@dcoufal  No worries. Thank you!
