### ISSUE TITLE
HLSWriter.write fatal error using CocoaPods

### ISSUE THREAD

**Issue by chowey** [Comcast/mamba#6]
### Expected Behavior

Install mamba with CocoaPods. HLSWriter.write should work.

### Observed Behavior

HLSWriter.write gives an error `Fatal error: Unable to find framework bundle: file /path/to/project/Pods/mamba/mambaSharedFramework/Mamba.swift, line 29`

### Workaround

In `Pods/mamba/Support Files/Info.plist`, change the "Bundle identifier" to "com.comcast.mamba".

**Comment by morrowa** [comment]
My suggested permanent fix for this issue will be to change `Mamba.version` to use `Bundle(for: HLSParser.self)` instead of using a hard-coded bundle identifier.

However, we should also update the Info.plist.

I'll submit a PR on Monday if @dcoufal doesn't get to it before me.

**Comment by dcoufal** [comment]
Yeah, i think we should use `Bundle(for: HLSParser.self)` as well. We'd have to do some post install shenanigans in the podspec to make it work.

Thanks @chowey ! We use carthage so we were blissfully ignorant. We'll update our tester apps (at https://github.com/dcoufal/mamba_test_apps) to testing writing as well (right now it only tests parsing)

**Comment by dcoufal** [comment]
Fixed in 1.0.1. Closing.
