### ISSUE TITLE
How could I add it in my project ? 

### ISSUE THREAD

**Issue by mamadfrhi** [Comcast/mamba#74]

**Comment by dcoufal** [comment]
@mamadfrhi 

If I understand the question, you are asking how you can use this code in your project.

We support both Carthage and Cocoapods. These are both dependency management solutions for Apple platforms. You can learn about them in general here https://medium.com/xcblog/swift-dependency-management-for-ios-3bcfc4771ec0 or by searching.

There's a good Carthage tutorial here: https://www.raywenderlich.com/416-carthage-tutorial-getting-started and the carthage project official site and docs are here: https://github.com/Carthage/Carthage

The official cocoapods install/getting started section is very good and is located at: https://cocoapods.org/

Finally, you could just download the code (there's a "clone or download" button on every github project on the front page, for us it's here: https://github.com/Comcast/mamba) and drag and drop the files into your project. I do not recommend this really, but it's possible.

I hope this helps. I'm going to close the issue as I think I've answered the question, but please let us know if I misunderstood.
