### ISSUE TITLE
Swift Package Manager support?

### ISSUE THREAD

**Issue by danielbyon** [Comcast/mamba#81]
Do you guys have any plans on adding SPM support? We're looking to move away from Carthage, now that SPM supports iOS/tvOS

**Comment by dcoufal** [comment]
We don't but that would be a welcome PR!

**Comment by theRealRobG** [comment]
Released in versions [2.4.0](https://github.com/Comcast/mamba/releases/tag/2.4.0) and [1.5.4](https://github.com/Comcast/mamba/releases/tag/1.5.4).
