### ISSUE TITLE
Updating podspec to include fix for static libraries

### ISSUE THREAD

**Issue by chaitanyabaranwal** [Comcast/mamba#93]
### Expected Behavior

Integrating `mamba` into XCode project through Cocoapods should raise no issue.

### Observed Behavior

Build error with the message `mamba/mamba-Swift.h` file not found`. Observed in Xcode 11.6.

### Open Questions

Seems like commit 56a03fdfc122fda7cf262f42be3aa3e9d240d75c fixes this issue, but the podspec is not pointing to the latest commit on the `develop` branch. Is it possible for the podspec to be updated?

**Comment by dcoufal** [comment]
Looks like we didn't do a release after the cocoapod patch-up PR.

I will do a 2.2.1 release when I get a moment. Thanks for pointing it out!

**Comment by dcoufal** [comment]
@chaitanyabaranwal We just released 2.2.1 with the fix so I'm closing. We are not pods users so if you have problems please submit another ticket.
